# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

### Health check
GET http://127.0.0.1:8000/api/v1/health
Accept: application/json



###
POST http://127.0.0.1:8000/api/v1/users
Content-Type: application/json

{
  "email": "admin@example.com",
  "username": "admin",
  "password": "123456"
}

###
POST http://127.0.0.1:8000/api/v1/auth/register
Content-Type: application/json

{
  "email": "new_admin@example.com",
  "username": "new_admin",
  "password": "123456"
}

###
POST http://127.0.0.1:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "new_admin@example.com",
  "password": "123456"
}

###
GET http://127.0.0.1:8000/api/v1/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOWQ1MDllMi1kYzA5LTRmNDgtYWViYy1kMmY2MmU3ZTY0ZmEiLCJleHAiOjE3Nzk4NTg5NzIsImVtYWlsIjoibmV3X2FkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIn0.grTZToOafF0j2iLIwv4eqI2vwlA54db-Iuxyu7IEDUw

###
POST http://127.0.0.1:8000/api/v1/catalog/categories
Content-Type: application/json

{
  "name": "Drinks",
  "slug": "drinks"
}

###
POST http://127.0.0.1:8000/api/v1/catalog/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxOWQ1MDllMi1kYzA5LTRmNDgtYWViYy1kMmY2MmU3ZTY0ZmEiLCJleHAiOjE3Nzk4NTg5NzIsImVtYWlsIjoibmV3X2FkbWluQGV4YW1wbGUuY29tIiwicm9sZSI6IkFETUlOIn0.grTZToOafF0j2iLIwv4eqI2vwlA54db-Iuxyu7IEDUw
Content-Type: application/json

{
  "category_id": "edb261a5-6ff4-483e-92de-233f4c246f1f",
  "name": "Coca-Cola 2L",
  "slug": "coca-cola-2l",
  "description": "Classic Coca-Cola drink",
  "price": 590,
  "sku": "COLA-2L",
  "stock_quantity": 100
}