# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

### Health check
GET http://127.0.0.1:8000/api/v1/health
Accept: application/json



###
POST http://127.0.0.1:8000/api/v1/users
Authorization: Bearer <ADMIN_TOKEN>
Content-Type: application/json

{
  "email": "admin@example.com",
  "username": "admin",
  "password": "123456"
}

###
POST http://127.0.0.1:8000/api/v1/auth/register
Content-Type: application/json

{
  "email": "admin@example.com",
  "username": "new_admin",
  "password": "123456"
}

###
POST http://127.0.0.1:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "john@example.com",
  "password": "123456"
}

###
GET http://127.0.0.1:8000/api/v1/users/me
Authorization: Bearer <CUSTOMER_TOKEN>
###
POST http://127.0.0.1:8000/api/v1/catalog/categories
Authorization: Bearer <ADMIN_TOKEN>
Content-Type: application/json

{
  "name": "Drinks",
  "slug": "drinks"
}

###
POST http://127.0.0.1:8000/api/v1/catalog/products
Authorization: Bearer <ADMIN_TOKEN>
Content-Type: application/json

{
  "category_id": "edb261a5-6ff4-483e-92de-233f4c246f1f",
  "name": "Coca-Cola 2L",
  "slug": "coca-cola-2l",
  "description": "Classic Coca-Cola drink",
  "price": 590,
  "sku": "COLA-2L",
  "stock_quantity": 100
}

###
GET http://127.0.0.1:8000/api/v1/cart
Authorization: Bearer <CUSTOMER_TOKEN>


###
POST http://127.0.0.1:8000/api/v1/cart/items
Authorization: Bearer <CUSTOMER_TOKEN>
Content-Type: application/json

{
  "product_id": "c5dc6ed9-38e0-4ce6-a760-455e9c9af28f",
  "quantity": 2
}
###
PATCH http://127.0.0.1:8000/api/v1/cart/items/2b6dde5b-df02-435a-a478-7e50469d45bc
Authorization: Bearer <CUSTOMER_TOKEN>
Content-Type: application/json

{
  "quantity": 5
}

###
DELETE http://127.0.0.1:8000/api/v1/cart/items/2b6dde5b-df02-435a-a478-7e50469d45bc
Authorization: Bearer <CUSTOMER_TOKEN>

###
DELETE http://127.0.0.1:8000/api/v1/cart
Authorization: Bearer <CUSTOMER_TOKEN>

###
POST http://127.0.0.1:8000/api/v1/orders/checkout
Authorization: Bearer <CUSTOMER_TOKEN>

###
GET http://127.0.0.1:8000/api/v1/orders
Authorization: Bearer <CUSTOMER_TOKEN>

###
GET http://127.0.0.1:8000/api/v1/orders/fe7b4b9d-3994-422d-bdac-4f7cf79ccf7f
Authorization: Bearer <ADMIN_TOKEN>


###
POST http://127.0.0.1:8000/api/v1/orders/49a5806c-0db8-44a0-9b46-da02f38f95dd/cancel
Authorization: Bearer <ADMIN_TOKEN>


###
POST http://127.0.0.1:8000/api/v1/payments/orders/a05a01f6-e455-4433-913f-abdc8b2b15a6
Authorization: Bearer <CUSTOMER_TOKEN>

###
POST http://127.0.0.1:8000/api/v1/payments/b01bd22d-b494-4809-89d9-497e100e2636/success
Authorization: Bearer <CUSTOMER_TOKEN>


###
POST http://127.0.0.1:8000/api/v1/orders/a05a01f6-e455-4433-913f-abdc8b2b15a6/complete
Authorization: Bearer <ADMIN_TOKEN>


###
GET http://127.0.0.1:8000/api/v1/catalog/products?page=1&limit=10

###
GET http://127.0.0.1:8000/api/v1/orders?page=1&limit=10
Authorization: Bearer <ADMIN_TOKEN>

###
GET http://127.0.0.1:8000/api/v1/orders/admin?page=1&limit=10
Authorization: Bearer <ADMIN_TOKEN>


###
GET http://127.0.0.1:8000/api/v1/catalog/categories?page=1&limit=10
###
GET http://127.0.0.1:8000/api/v1/catalog/products/239d5e1c-0be5-4f1c-a3ac-bfae1fe727bb

